services:
  - type: web
    name: myportfolio
    runtime: node
    rootDir: .
    buildCommand: npm install && npm run build && cd backend && npm install
    startCommand: node backend/server.js
    envVars:
      - key: PORT
        value: 10000
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: TO_EMAIL
        sync: false

